import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 text-neutral-100`}
      >
        <div className="min-h-screen flex">
          <aside className="w-56 bg-neutral-950 border-r border-neutral-800 flex flex-col p-6 gap-4 shadow-sm">
            <h1 className="text-xl font-bold mb-6 text-neutral-300">お掃除当番管理</h1>
            <nav className="flex flex-col gap-2">
              <a href="/" className="hover:underline text-cyan-400">トップページ</a>
              <a href="/admin" className="hover:underline text-cyan-400">管理画面</a>
            </nav>
          </aside>
          <main className="flex-1 p-8 bg-neutral-900 text-neutral-100 min-h-screen flex flex-col items-center justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}