name: CI

on:
  pull_request:
    branches: ['main']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run format
      - run: npm run type-check
      - run: npm run lint
      - run: npm run test:coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: kokutaro/cleaning-duty-manager
          files: 'coverage/**/lcov.info'